version: '3.8'

services:
  db:
    image: postgres
    container_name: db-task-flow
    restart: always
    env_file:
      - .env
    ports:
      - 5434:5432
    volumes:
      - ./data/db_data:/var/lib/postgresql/data

  api:
    build:
      context: .
    restart: always
    container_name: api-task-flow
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    command: 'npx prisma migrate dev && npm start:dev'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  db:
    name: nest-prisma-docker-db
