version: '3.8'

services:
  db:
    image: postgres
    container_name: db-task-flow
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./data/db_data:/var/lib/postgresql/data

  api:
    build:
      context: .
    restart: always
    container_name: api-task-flow
    command: 'pnpm prisma migrate dev && pnpm start:dev'
    networks:
      - api-task-flow-network
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

networks:
  api-task-flow-network:
